version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: acunathink/cityshop
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/backend/
    depends_on:
      - backend
